### ISSUE TITLE
Add Group attribute to Milestones objects in GovReady-Q.

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1016]
There was an existing 'group' in views. Used 'poam_group' instead.

- [x] Add field `poam_group` to `controls.models.Poam` class
- [x] Create and run migration for modified model
- [x] Add field `poam_group` to `controls.forms.PoamForm` class so field will appear in form
- [x] Add field 'poam_group' to controls. views
- [x]  Add test for `poam_group` field in `controls.tests`
- [x] Confirm that field shows up on form
- [x] Confirm value is saved and redisplayed
- [x] Run tests

**Comment by peterkaminski** [comment]
## Testing

We ran tests.  We did not see our test statement about `poam_group`, but we are not sure POA&Ms were tested at all. There were a number of other errors which we believe were not caused by our changes.  We stopped at that point because further debugging seemed out of scope of this card.

Test results attached.

[test-results-20200909T1143EDT.txt](https://github.com/GovReady/govready-q/files/5196346/test-results-20200909T1143EDT.txt)

**Comment by gregelin** [comment]
@peterkaminski @cityinohio2019 Thanks for update. Will take a look.

**Comment by gregelin** [comment]
@peterkaminski - My tests were all OK. One thing I have noticed is that when I run the tests I should not do anything else on the computer (or be very careful) so as to avoid accidentally sending a keystroke to Selenium running Chrome.

**Comment by peterkaminski** [comment]
@gregelin, great news that they worked for you.  It probably was a keystroke thing -- I wasn't being careful while Selenium was running to stay out of its way.

(And am I misremembering, or was there a problem running successful tests when Zoom was running, even if you didn't do anything else?)

**Comment by gregelin** [comment]
Closed with PR # #1021
