### ISSUE TITLE
Establish consistent release process and CD pipeline

### ISSUE THREAD

**Issue by pburkholder** [GovReady/govready-q#114]
As a GovReady devop, \
I'm confident releases go out only from a authenticated source
and are automated for consistency.

Evaluate:
- [x] Travis CI: https://docs.travis-ci.com/user/deployment/cloudfoundry
- [x] Concourse: https://blog.pivotal.io/pivotal-cloud-foundry/products/continuous-deployment-from-github-to-pws-via-concourse
- [x] CicleCI: https://circleci.com/docs/deploy-bluemix/
