### ISSUE TITLE
Do not automatically grant project participants full portfolio membership when Revise permissions during 0.8.6 to 0.9.0 migration

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#741]
# Description
Based on feedback from customer, we do not want to make a guest/participant in a Project automatically a member to the Portfolio to which the Project belongs.

Assigning Project membership creates a bad situation in a larger enterprises which currently use 0.8.6 with a single organization. In their 0.8.6 installations most users only have access to a single Project and a few users have access to all projects. When the single primary organization is converted to a Portfolio, granting each Project participant Portfolio membership results in all users having access to all projects.

# TODO
- [ ] Do we need to create a new permissions?
- [ ] Do we need to call a user a "portfolio guest"?
- [ ] Update the migration documentation's section on permissions to be accurate to the changes
- [ ] What happens in 0.9.0 when a user is invited to a project, but not to portfolio?
- [ ] How do we a unit test for this?

**Comment by gregelin** [comment]
This issue was addressed PR #742.
